# =========================
# = Application Config
# =========================
server:
  port: ${SERVER_PORT:8089}
  servlet:
    context-path: /leaves-service
spring:
  application:
    name: leaves-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}

  # =========================
  # = Jackson Config
  # =========================
  jackson:
    default-property-inclusion: non_null

  # =========================
  # = MongoDB Config
  # =========================
  data:
    mongodb:
      uri: mongodb://localhost:27017/ms-leaves
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy
      auto-index-creation: true
  # = Kafka Config
  # =========================
  kafka:
    client-id: ${spring.application.name}
    bootstrap-servers: localhost:9092
    consumer:
      group-id: leave-service-consumers
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer